version: "3.7"

services:
  node:
    build:
      context: .
    container_name: tailwind-css-with-nuxtjs-app
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: volume
        source: node-modules-data
        target: /var/www/html/node_modules
    stdin_open: true
    tty: true

volumes:
  node-modules-data:
